### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ghost** [PetteriM1/Snow#1]
Plugin doesn't change weather to rain.

**Comment by PetteriM1** [comment]
Needs more information.

Which version of Nukkit and the plugin you are running? In which case does that happen? After joining or level changing? Are the chunks on that area already generated? What other plugins you have? Something what could affect to the weather?

**Comment by ghost** [comment]
Nukkit version (/version): This server is running Nukkit git-a5f8c5a 「」 implementing API version 1.0.9 for Minecraft: BE v1.14.0 (protocol version 389)
Other Plugins (/plugins): Plugins (27): LoveDiguise v1, EconomySystem v0.4, EssentialsNK v2.0, ScoreboardPlugin v1.0, LobbySystem v1.2, SimpleScoreboards v3.1, MaxEnchants v1.1-SNAPSHOT, KotlinLib v1.1, PlaceholderAPI v1.3.1, SimpleAnnouncer v0.5, NPC v2.2.4, Snow v1.1.0, CloudNet-Bridge v1.0, CloudNet-Signs v1.0, ZChat v1.0.16-Beta, PmChair v2.0.1, DbLib v0.2.4, FastAsyncWorldEdit v19.07.06-e994c76-1276-22.2.2, MultiWorld v1.0, FDevTools v{pom.version}, Holograms v3.1.3, LuckPerms v4.4.19, PlugMan v1.0, WelcomeForm v1.1, Residence v1.2, BungeeCommands v1.0, OnlyProxyJoin v1.0
Weather is working correctly, if snow isn't installed. The chunks are getting updatetd to snow biome, if plugin is installed
There is no plugin, that affects weather. If I join, no snow appears and the weather is not changed. /weather command doesn't work.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44708000/70849985-be468e00-1e85-11ea-8099-ca64f9a99878.png)

**Comment by PetteriM1** [comment]
Is this the spawn area?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
but when i disable the plugin and type /weather rain, snow appears

**Comment by ghost** [comment]
i disabled the plugin:
![image](https://user-images.githubusercontent.com/44708000/70850319-2ba7ee00-1e89-11ea-9b6a-acad9fff6265.png)

**Comment by ghost** [comment]
and I run the cmd /weather rain

**Comment by PetteriM1** [comment]
Is the result same if you put rain on and rejoin without snow plugin enabled as it is if you rejoin with snow plugin enabled when you haven't touched to the weather command?

**Comment by ghost** [comment]
when i put rain on without snow plugin enabled: it rains. when i rejoin: it rains.
when i don't touch weather command and snow plugin is enabled, it doesn't rain. when i rejoin: it doesn't rain

**Comment by PetteriM1** [comment]
I'm unable to reproduce that. Try: /weather clear, restart server and join
Also make sure that the snowing is enabled for that world in the config

**Comment by ghost** [comment]
everything done, don't work

**Comment by PetteriM1** [comment]
Can you show your config?

**Comment by ghost** [comment]
```yaml
# 0 = snow
# 1 = make biome to plains
mode: 0

# list of worlds where snowing is enabled
worlds:
  - "Lobby"
```

**Comment by PetteriM1** [comment]
and what is your world called?

**Comment by ghost** [comment]
Lobby

**Comment by ghost** [comment]
The biome is changing, but snow isn't working

**Comment by PetteriM1** [comment]
Can you confirm it with no other plugins installed?

**Comment by ghost** [comment]
lol, without plugins, it's working...

**Comment by ghost** [comment]
do you have an idea, what could be the issue?

**Comment by PetteriM1** [comment]
Put your plugins back one by one and you will see when it stops working

**Comment by ghost** [comment]
I installed every plugin, that I had on the lobby server and snow is working, but on my lobby server, it doesn't

**Comment by ghost** [comment]
@PetteriM1

**Comment by ghost** [comment]
do u have an idea?
